### ISSUE TITLE
Opening an event that has a Contentful hosted image in the description causes the app to crash on Android

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#103]
Tested on Samsung Galaxy S8 (also happens on Jan's Pixel 2)

The app crashes immediately if you open the event with the horrible name: 
![20180408_110709](https://user-images.githubusercontent.com/33623842/38466181-1cc49e84-3b1d-11e8-9a51-b8d3084341a7.jpg)

Link to contentful event: https://app.contentful.com/spaces/n2o4hgsv6wcx/entries/1Yo3rc8E6ooSOCoS846qmc

The crash only seems to occur in the hockeyapp alpha and beta builds. If you build the app locally it opens the event and loads the contents in the event description without crashing.

I tested the earliest available hockeyapp alpha build (1775) and it happens there as well.

**Comment by declanslevin** [comment]
I now think that it is any event with a Contentful host image in the description that causes the crash - I tried this with a new event (Tywin Lannister - https://app.contentful.com/spaces/n2o4hgsv6wcx/entries/3QJi2eoxd6oiqK6OeuK2M6) which has nothing else in the description, except for a Contentful hosted image. It crashes instantly once the event is opened. Updating the bug title.

**Comment by zoeabryant** [comment]
<img width="236" alt="screen shot 2018-05-04 at 15 36 51" src="https://user-images.githubusercontent.com/5781504/39633834-033f2292-4fb1-11e8-88be-75264f9c2b82.png">

Nesting Views under Text is an iOS only feature: https://facebook.github.io/react-native/docs/text.html#nested-views-ios-only

**Comment by declanslevin** [comment]
Is there a way to restrict Contentful from allowing editors to nest images in the Description? If not, our only option is probably to update the Content Editor Guide to state that they shouldn't do this.

**Comment by RGBboy** [comment]
Just replaying the PR here and reopening so this gets a proper chance for QA.

The root of #103 comes from our markdown renderer. Essentially it nests Image components within Text components, which is no longer supported by Android.

After a bit of a discussion around this we decided to disable images from rendering in the existing markdown renderer. We will also be changing long text fields in contentful to be rendered as multiple line input, rather than the markdown input to avoid other markdown being used by content editors. The main reason for this is that the various elements that markdown can produce have not been designed for and therefore often do not look very good. We can rethink this later when we design for other cases markdown brings.

**Comment by declanslevin** [comment]
This is fixed
